
#pragma once

#include <battle/init.h>
#include <data/moves.h>
#include <data/species.h>

namespace SampleTeams {
using enum Data::Move;
using Data::Species;

constexpr std::array<Init::Team, 16> teams{
    Init::Team{
        Init::Set{Species::Starmie, {Surf, Thunderbolt, ThunderWave, Recover}},
        Init::Set{Species::Exeggutor,
                  {SleepPowder, Psychic, StunSpore, Explosion}},
        Init::Set{Species::Rhydon,
                  {Earthquake, BodySlam, Substitute, TailWhip}},
        Init::Set{Species::Chansey, {Sing, IceBeam, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, HyperBeam, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
    Init::Team{
        Init::Set{Species::Starmie,
                  {Blizzard, Thunderbolt, ThunderWave, Recover}},
        Init::Set{Species::Exeggutor,
                  {SleepPowder, Psychic, MegaDrain, Explosion}},
        Init::Set{Species::Zapdos,
                  {Thunderbolt, DrillPeck, ThunderWave, Agility}},
        Init::Set{Species::Chansey,
                  {IceBeam, Thunderbolt, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Earthquake, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
    Init::Team{
        Init::Set{Species::Starmie, {Blizzard, Psychic, ThunderWave, Recover}},
        Init::Set{Species::Exeggutor,
                  {SleepPowder, Psychic, DoubleEdge, Explosion}},
        Init::Set{Species::Alakazam,
                  {Psychic, SeismicToss, ThunderWave, Recover}},
        Init::Set{Species::Chansey,
                  {IceBeam, Thunderbolt, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, HyperBeam, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
    Init::Team{
        Init::Set{Species::Jynx, {LovelyKiss, Blizzard, Psychic, Rest}},
        Init::Set{Species::Starmie, {Surf, Thunderbolt, ThunderWave, Recover}},
        Init::Set{Species::Alakazam,
                  {Psychic, SeismicToss, ThunderWave, Recover}},
        Init::Set{Species::Chansey,
                  {IceBeam, Counter, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, HyperBeam, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
    Init::Team{
        Init::Set{Species::Jynx, {LovelyKiss, Blizzard, Psychic, Rest}},
        Init::Set{Species::Starmie, {Surf, Thunderbolt, ThunderWave, Recover}},
        Init::Set{Species::Zapdos,
                  {Thunderbolt, DrillPeck, ThunderWave, Agility}},
        Init::Set{Species::Chansey,
                  {IceBeam, Counter, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Earthquake, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
    Init::Team{
        Init::Set{Species::Jynx, {LovelyKiss, Blizzard, Psychic, Rest}},
        Init::Set{Species::Starmie, {Surf, Thunderbolt, ThunderWave, Recover}},
        Init::Set{Species::Rhydon,
                  {Earthquake, BodySlam, Substitute, TailWhip}},
        Init::Set{Species::Chansey,
                  {IceBeam, Thunderbolt, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, HyperBeam, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
    Init::Team{
        Init::Set{Species::Jynx, {LovelyKiss, Blizzard, Psychic, Rest}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, Rest}},
        Init::Set{Species::Alakazam,
                  {Psychic, SeismicToss, ThunderWave, Recover}},
        Init::Set{Species::Chansey,
                  {IceBeam, Thunderbolt, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, HyperBeam, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
    Init::Team{
        Init::Set{Species::Starmie, {Blizzard, Psychic, ThunderWave, Recover}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, Rest}},
        Init::Set{Species::Jolteon,
                  {Thunderbolt, DoubleKick, ThunderWave, Rest}},
        Init::Set{Species::Chansey, {Sing, IceBeam, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Earthquake, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, FireBlast}},
    },
    Init::Team{
        Init::Set{Species::Starmie, {Blizzard, Psychic, ThunderWave, Recover}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, Rest}},
        Init::Set{Species::Alakazam,
                  {Psychic, SeismicToss, ThunderWave, Recover}},
        Init::Set{Species::Chansey, {Sing, IceBeam, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, HyperBeam, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
    Init::Team{
        Init::Set{Species::Alakazam,
                  {Psychic, SeismicToss, ThunderWave, Recover}},
        Init::Set{Species::Starmie, {Surf, Thunderbolt, ThunderWave, Recover}},
        Init::Set{Species::Rhydon,
                  {Earthquake, BodySlam, Substitute, RockSlide}},
        Init::Set{Species::Chansey, {Sing, IceBeam, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, IceBeam, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
    Init::Team{
        Init::Set{Species::Alakazam,
                  {Psychic, SeismicToss, ThunderWave, Recover}},
        Init::Set{Species::Exeggutor,
                  {SleepPowder, Psychic, MegaDrain, Explosion}},
        Init::Set{Species::Slowbro, {Amnesia, Surf, ThunderWave, Rest}},
        Init::Set{Species::Chansey,
                  {SeismicToss, Reflect, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Earthquake, Rest}},
        Init::Set{Species::Tauros,
                  {BodySlam, HyperBeam, Blizzard, Thunderbolt}},
    },
    Init::Team{
        Init::Set{Species::Gengar, {Hypnosis, Psychic, Thunderbolt, Explosion}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, Rest}},
        Init::Set{Species::Alakazam,
                  {Psychic, SeismicToss, ThunderWave, Recover}},
        Init::Set{Species::Chansey, {Sing, IceBeam, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, HyperBeam, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
    Init::Team{
        Init::Set{Species::Gengar, {Hypnosis, Psychic, Thunderbolt, Explosion}},
        Init::Set{Species::Exeggutor,
                  {SleepPowder, Psychic, StunSpore, Explosion}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Rest, Explosion}},
        Init::Set{Species::Chansey,
                  {SeismicToss, Reflect, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {BodySlam, HyperBeam, Blizzard, Thunderbolt}},
    },
    Init::Team{
        Init::Set{Species::Gengar, {Hypnosis, Psychic, Thunderbolt, Explosion}},
        Init::Set{Species::Exeggutor,
                  {SleepPowder, Psychic, StunSpore, Explosion}},
        Init::Set{Species::Starmie, {Surf, Thunderbolt, ThunderWave, Recover}},
        Init::Set{Species::Chansey,
                  {IceBeam, Thunderbolt, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Earthquake, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
    Init::Team{
        Init::Set{Species::Gengar,
                  {Hypnosis, NightShade, Thunderbolt, Explosion}},
        Init::Set{Species::Starmie, {Surf, Thunderbolt, ThunderWave, Recover}},
        Init::Set{Species::Zapdos,
                  {Thunderbolt, DrillPeck, ThunderWave, Agility}},
        Init::Set{Species::Chansey, {Sing, IceBeam, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, Earthquake, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
    Init::Team{
        Init::Set{Species::Gengar, {Hypnosis, Psychic, Thunderbolt, Explosion}},
        Init::Set{Species::Starmie, {Surf, Thunderbolt, ThunderWave, Recover}},
        Init::Set{Species::Alakazam,
                  {Psychic, SeismicToss, ThunderWave, Recover}},
        Init::Set{Species::Chansey, {Sing, IceBeam, ThunderWave, SoftBoiled}},
        Init::Set{Species::Snorlax, {BodySlam, Reflect, HyperBeam, Rest}},
        Init::Set{Species::Tauros, {BodySlam, HyperBeam, Blizzard, Earthquake}},
    },
};

constexpr std::array<Init::Team, 2> benchmark_teams{
    Init::Team{
        Init::Set{Species::Jynx, {Blizzard, LovelyKiss, Psychic, Rest}},
        Init::Set{Species::Chansey, {IceBeam, Sing, SoftBoiled, Thunderbolt}},
        Init::Set{Species::Cloyster, {Blizzard, Clamp, Explosion, HyperBeam}},
        Init::Set{Species::Rhydon,
                  {BodySlam, Earthquake, RockSlide, Substitute}},
        Init::Set{Species::Starmie,
                  {Blizzard, Recover, Thunderbolt, ThunderWave}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
    Init::Team{
        Init::Set{Species::Alakazam,
                  {Psychic, Recover, SeismicToss, ThunderWave}},
        Init::Set{Species::Chansey,
                  {Reflect, SeismicToss, SoftBoiled, ThunderWave}},
        Init::Set{Species::Exeggutor,
                  {Explosion, Psychic, SleepPowder, StunSpore}},
        Init::Set{Species::Lapras, {Blizzard, HyperBeam, Sing, Thunderbolt}},
        Init::Set{Species::Snorlax,
                  {BodySlam, Earthquake, HyperBeam, SelfDestruct}},
        Init::Set{Species::Tauros,
                  {Blizzard, BodySlam, Earthquake, HyperBeam}}},
};

} // namespace SampleTeams
