#!/usr/bin/env bash

rm -rf cpp/build/Release/*
mkdir -p cpp/build/Release
cmake cpp \
  -B "$BUILD_DIR" \
  -G "Ninja" \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_C_COMPILER=gcc \
  -DCMAKE_CXX_COMPILER=g++ \
  -DGMP_LIBRARY:FILEPATH="C:/msys64/mingw64/lib/libgmp.a" \
  -DGMP_INCLUDE_DIR:PATH="C:/msys64/mingw64/include" \
  -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=../../../src/oak/_native \
  -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=../../../src/oak/_bin
cmake --build cpp/build/Release
