#pragma once

#include <array>

#include <format/random-battles/data.h>

namespace RandomBattlesData {

using PKMN::Data::Species;
using enum PKMN::Data::Move;
using PKMN::Data::get_types;
using PKMN::Data::Move;
using PKMN::Data::Type;

struct RandomSetEntry {
  static constexpr uint8_t max_moves{9};
  static constexpr uint8_t max_exclusive_moves{9};
  static constexpr uint8_t max_essential_moves{3};
  static constexpr uint8_t max_combo_moves{4};

  uint8_t level;
  uint8_t n_moves;
  uint8_t n_exclusive_moves;
  uint8_t n_essential_moves;
  uint8_t n_combo_moves;

  std::array<Move, max_moves> moves;
  std::array<Move, max_exclusive_moves> exclusive_moves;
  std::array<Move, max_essential_moves> essential_moves;
  std::array<Move, max_combo_moves> combo_moves;

  std::array<uint8_t, 6> weaknesses{};
  std::array<Type, 2> types{};
};

constexpr std::array<RandomSetEntry, 152> RANDOM_SET_DATA{

    RandomSetEntry{},
    // none  not found in data.json
    RandomSetEntry{89,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, RazorLeaf, SleepPowder, SwordsDance, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Bulbasaur),
                   get_types(Species::Bulbasaur)},
    RandomSetEntry{80,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, RazorLeaf, SleepPowder, SwordsDance, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Ivysaur),
                   get_types(Species::Ivysaur)},
    RandomSetEntry{
        74,
        3,
        3,
        0,
        0,
        {BodySlam, RazorLeaf, SleepPowder, None, None, None, None, None, None},
        {HyperBeam, SwordsDance, SwordsDance, None, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Venusaur),
        get_types(Species::Venusaur)},
    RandomSetEntry{90,
                   5,
                   0,
                   2,
                   4,
                   {Counter, SeismicToss, SeismicToss, Slash, Slash, None, None,
                    None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {BodySlam, FireBlast, None},
                   {BodySlam, FireBlast, Submission, SwordsDance},
                   getImportantWeaknesses(Species::Charmander),
                   get_types(Species::Charmander)},
    RandomSetEntry{81,
                   5,
                   0,
                   2,
                   4,
                   {Counter, SeismicToss, SeismicToss, Slash, Slash, None, None,
                    None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {BodySlam, FireBlast, None},
                   {BodySlam, FireBlast, Submission, SwordsDance},
                   getImportantWeaknesses(Species::Charmeleon),
                   get_types(Species::Charmeleon)},
    RandomSetEntry{
        74,
        4,
        0,
        0,
        4,
        {BodySlam, Earthquake, FireBlast, Slash, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {None, None, None},
        {Earthquake, FireBlast, HyperBeam, SwordsDance},
        getImportantWeaknesses(Species::Charizard),
        get_types(Species::Charizard)},
    RandomSetEntry{
        90,
        2,
        3,
        2,
        0,
        {BodySlam, Counter, None, None, None, None, None, None, None},
        {HydroPump, Surf, Surf, None, None, None, None, None, None},
        {Blizzard, SeismicToss, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Squirtle),
        get_types(Species::Squirtle)},
    RandomSetEntry{
        82,
        3,
        3,
        2,
        0,
        {Counter, Rest, SeismicToss, None, None, None, None, None, None},
        {HydroPump, Surf, Surf, None, None, None, None, None, None},
        {Blizzard, BodySlam, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Wartortle),
        get_types(Species::Wartortle)},
    RandomSetEntry{75,
                   2,
                   3,
                   2,
                   0,
                   {Earthquake, Rest, None, None, None, None, None, None, None},
                   {HydroPump, Surf, Surf, None, None, None, None, None, None},
                   {Blizzard, BodySlam, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Blastoise),
                   get_types(Species::Blastoise)},
    RandomSetEntry{},
    // caterpie  not found in data.json
    RandomSetEntry{},
    // metapod  not found in data.json
    RandomSetEntry{
        77,
        3,
        4,
        0,
        0,
        {Psychic, SleepPowder, StunSpore, None, None, None, None, None, None},
        {DoubleEdge, HyperBeam, MegaDrain, Substitute, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Butterfree),
        get_types(Species::Butterfree)},
    RandomSetEntry{},
    // weedle  not found in data.json
    RandomSetEntry{},
    // kakuna  not found in data.json
    RandomSetEntry{
        81,
        3,
        3,
        0,
        0,
        {HyperBeam, SwordsDance, Twineedle, None, None, None, None, None, None},
        {Agility, Agility, MegaDrain, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Beedrill),
        get_types(Species::Beedrill)},
    RandomSetEntry{93,
                   5,
                   3,
                   1,
                   4,
                   {Agility, Agility, QuickAttack, QuickAttack, SkyAttack, None,
                    None, None, None},
                   {MirrorMove, SandAttack, Substitute, None, None, None, None,
                    None, None},
                   {DoubleEdge, None, None},
                   {Agility, DoubleEdge, QuickAttack, SkyAttack},
                   getImportantWeaknesses(Species::Pidgey),
                   get_types(Species::Pidgey)},
    RandomSetEntry{85,
                   5,
                   3,
                   1,
                   4,
                   {Agility, Agility, QuickAttack, QuickAttack, SkyAttack, None,
                    None, None, None},
                   {MirrorMove, SandAttack, Substitute, None, None, None, None,
                    None, None},
                   {DoubleEdge, None, None},
                   {Agility, DoubleEdge, QuickAttack, SkyAttack},
                   getImportantWeaknesses(Species::Pidgeotto),
                   get_types(Species::Pidgeotto)},
    RandomSetEntry{
        76,
        3,
        9,
        0,
        0,
        {Agility, DoubleEdge, HyperBeam, None, None, None, None, None, None},
        {MirrorMove, Reflect, SandAttack, SkyAttack, SkyAttack, Substitute,
         QuickAttack, QuickAttack, QuickAttack},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Pidgeot),
        get_types(Species::Pidgeot)},
    RandomSetEntry{
        89,
        3,
        6,
        0,
        0,
        {Blizzard, BodySlam, SuperFang, None, None, None, None, None, None},
        {DoubleEdge, Thunderbolt, Thunderbolt, Thunderbolt, QuickAttack,
         QuickAttack, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Rattata),
        get_types(Species::Rattata)},
    RandomSetEntry{75,
                   4,
                   0,
                   0,
                   0,
                   {Blizzard, BodySlam, HyperBeam, SuperFang, None, None, None,
                    None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Raticate),
                   get_types(Species::Raticate)},
    RandomSetEntry{
        89,
        3,
        4,
        0,
        0,
        {Agility, DoubleEdge, DrillPeck, None, None, None, None, None, None},
        {Leer, Mimic, MirrorMove, Substitute, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Spearow),
        get_types(Species::Spearow)},
    RandomSetEntry{75,
                   4,
                   0,
                   0,
                   0,
                   {Agility, DoubleEdge, DrillPeck, HyperBeam, None, None, None,
                    None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Fearow),
                   get_types(Species::Fearow)},
    RandomSetEntry{
        90,
        4,
        0,
        0,
        0,
        {BodySlam, Earthquake, Glare, RockSlide, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Ekans),
        get_types(Species::Ekans)},
    RandomSetEntry{
        78,
        3,
        3,
        0,
        0,
        {Earthquake, Glare, HyperBeam, None, None, None, None, None, None},
        {BodySlam, RockSlide, RockSlide, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Arbok),
        get_types(Species::Arbok)},
    RandomSetEntry{
        87,
        3,
        4,
        0,
        0,
        {Surf, Thunderbolt, ThunderWave, None, None, None, None, None, None},
        {Agility, BodySlam, SeismicToss, SeismicToss, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Pikachu),
        get_types(Species::Pikachu)},
    RandomSetEntry{
        74,
        3,
        6,
        0,
        0,
        {Surf, Thunderbolt, ThunderWave, None, None, None, None, None, None},
        {Agility, BodySlam, HyperBeam, HyperBeam, SeismicToss, Thunder, None,
         None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Raichu),
        get_types(Species::Raichu)},
    RandomSetEntry{88,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, Earthquake, RockSlide, SwordsDance, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Sandshrew),
                   get_types(Species::Sandshrew)},
    RandomSetEntry{76,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, Earthquake, RockSlide, SwordsDance, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Sandslash),
                   get_types(Species::Sandslash)},
    RandomSetEntry{
        90,
        3,
        2,
        0,
        0,
        {Blizzard, BodySlam, Thunderbolt, None, None, None, None, None, None},
        {DoubleEdge, DoubleKick, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::NidoranF),
        get_types(Species::NidoranF)},
    RandomSetEntry{
        82,
        3,
        3,
        0,
        0,
        {Blizzard, BodySlam, Thunderbolt, None, None, None, None, None, None},
        {BubbleBeam, DoubleEdge, DoubleKick, None, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Nidorina),
        get_types(Species::Nidorina)},
    RandomSetEntry{
        74,
        3,
        3,
        0,
        0,
        {Blizzard, Earthquake, Thunderbolt, None, None, None, None, None, None},
        {BodySlam, BodySlam, Substitute, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Nidoqueen),
        get_types(Species::Nidoqueen)},
    RandomSetEntry{
        90,
        3,
        2,
        0,
        0,
        {Blizzard, BodySlam, Thunderbolt, None, None, None, None, None, None},
        {DoubleEdge, DoubleKick, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::NidoranM),
        get_types(Species::NidoranM)},
    RandomSetEntry{
        82,
        3,
        3,
        0,
        0,
        {Blizzard, BodySlam, Thunderbolt, None, None, None, None, None, None},
        {BubbleBeam, DoubleEdge, DoubleKick, None, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Nidorino),
        get_types(Species::Nidorino)},
    RandomSetEntry{
        74,
        3,
        3,
        0,
        0,
        {Blizzard, Earthquake, Thunderbolt, None, None, None, None, None, None},
        {BodySlam, RockSlide, Substitute, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Nidoking),
        get_types(Species::Nidoking)},
    RandomSetEntry{
        88,
        4,
        6,
        2,
        0,
        {BodySlam, BodySlam, SeismicToss, Thunderbolt, None, None, None, None,
         None},
        {Blizzard, Blizzard, Counter, Psychic, Sing, Sing, None, None, None},
        {Blizzard, ThunderWave, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Clefairy),
        get_types(Species::Clefairy)},
    RandomSetEntry{74,
                   5,
                   7,
                   1,
                   0,
                   {BodySlam, BodySlam, Thunderbolt, ThunderWave, ThunderWave,
                    None, None, None, None},
                   {Blizzard, Counter, HyperBeam, HyperBeam, Psychic, Sing,
                    Sing, None, None},
                   {Blizzard, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Clefable),
                   get_types(Species::Clefable)},
    RandomSetEntry{
        88,
        3,
        6,
        0,
        0,
        {BodySlam, ConfuseRay, FireBlast, None, None, None, None, None, None},
        {Flamethrower, Flamethrower, QuickAttack, Reflect, Substitute,
         Substitute, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Vulpix),
        get_types(Species::Vulpix)},
    RandomSetEntry{
        74,
        3,
        5,
        0,
        0,
        {BodySlam, ConfuseRay, FireBlast, None, None, None, None, None, None},
        {Flamethrower, HyperBeam, Reflect, Substitute, Substitute, None, None,
         None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Ninetales),
        get_types(Species::Ninetales)},
    RandomSetEntry{
        89,
        2,
        3,
        2,
        0,
        {Blizzard, BodySlam, None, None, None, None, None, None, None},
        {Counter, Sing, ThunderWave, None, None, None, None, None, None},
        {ThunderWave, SeismicToss, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Jigglypuff),
        get_types(Species::Jigglypuff)},
    RandomSetEntry{
        76,
        3,
        3,
        0,
        0,
        {Blizzard, BodySlam, ThunderWave, None, None, None, None, None, None},
        {Counter, HyperBeam, Sing, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Wigglytuff),
        get_types(Species::Wigglytuff)},
    RandomSetEntry{
        100,
        3,
        3,
        0,
        0,
        {ConfuseRay, DoubleEdge, MegaDrain, None, None, None, None, None, None},
        {Substitute, Substitute, WingAttack, None, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Zubat),
        get_types(Species::Zubat)},
    RandomSetEntry{78,
                   4,
                   0,
                   0,
                   0,
                   {ConfuseRay, DoubleEdge, HyperBeam, MegaDrain, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Golbat),
                   get_types(Species::Golbat)},
    RandomSetEntry{
        90,
        3,
        3,
        0,
        0,
        {DoubleEdge, MegaDrain, SleepPowder, None, None, None, None, None,
         None},
        {StunSpore, StunSpore, SwordsDance, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Oddish),
        get_types(Species::Oddish)},
    RandomSetEntry{
        82,
        3,
        3,
        0,
        0,
        {DoubleEdge, MegaDrain, SleepPowder, None, None, None, None, None,
         None},
        {StunSpore, StunSpore, SwordsDance, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Gloom),
        get_types(Species::Gloom)},
    RandomSetEntry{
        76,
        3,
        3,
        0,
        0,
        {BodySlam, MegaDrain, SleepPowder, None, None, None, None, None, None},
        {StunSpore, StunSpore, SwordsDance, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Vileplume),
        get_types(Species::Vileplume)},
    RandomSetEntry{
        90,
        3,
        3,
        0,
        0,
        {BodySlam, MegaDrain, Spore, None, None, None, None, None, None},
        {StunSpore, StunSpore, SwordsDance, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Paras),
        get_types(Species::Paras)},
    RandomSetEntry{
        77,
        3,
        7,
        0,
        0,
        {BodySlam, MegaDrain, Spore, None, None, None, None, None, None},
        {HyperBeam, Slash, StunSpore, StunSpore, StunSpore, SwordsDance,
         SwordsDance, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Parasect),
        get_types(Species::Parasect)},
    RandomSetEntry{
        88,
        3,
        2,
        0,
        0,
        {Psychic, SleepPowder, StunSpore, None, None, None, None, None, None},
        {DoubleEdge, MegaDrain, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Venonat),
        get_types(Species::Venonat)},
    RandomSetEntry{
        74,
        3,
        2,
        0,
        0,
        {Psychic, SleepPowder, StunSpore, None, None, None, None, None, None},
        {DoubleEdge, MegaDrain, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Venomoth),
        get_types(Species::Venomoth)},
    RandomSetEntry{
        86,
        3,
        2,
        0,
        0,
        {Earthquake, RockSlide, Slash, None, None, None, None, None, None},
        {BodySlam, Substitute, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Diglett),
        get_types(Species::Diglett)},
    RandomSetEntry{
        73,
        3,
        2,
        0,
        0,
        {Earthquake, RockSlide, Slash, None, None, None, None, None, None},
        {BodySlam, Substitute, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Dugtrio),
        get_types(Species::Dugtrio)},
    RandomSetEntry{85,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, BubbleBeam, Slash, Thunderbolt, None, None, None,
                    None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Meowth),
                   get_types(Species::Meowth)},
    RandomSetEntry{
        73,
        3,
        2,
        0,
        0,
        {BodySlam, BubbleBeam, Slash, None, None, None, None, None, None},
        {HyperBeam, Thunderbolt, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Persian),
        get_types(Species::Persian)},
    RandomSetEntry{
        89,
        3,
        5,
        0,
        0,
        {Amnesia, Blizzard, Surf, None, None, None, None, None, None},
        {BodySlam, HydroPump, Rest, SeismicToss, SeismicToss, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Psyduck),
        get_types(Species::Psyduck)},
    RandomSetEntry{
        75,
        3,
        5,
        0,
        0,
        {Amnesia, Blizzard, Surf, None, None, None, None, None, None},
        {BodySlam, HydroPump, Rest, Rest, SeismicToss, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Golduck),
        get_types(Species::Golduck)},
    RandomSetEntry{
        89,
        3,
        3,
        0,
        0,
        {BodySlam, RockSlide, Submission, None, None, None, None, None, None},
        {Counter, LowKick, MegaKick, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Mankey),
        get_types(Species::Mankey)},
    RandomSetEntry{
        76,
        4,
        4,
        2,
        0,
        {RockSlide, RockSlide, RockSlide, Thunderbolt, None, None, None, None,
         None},
        {Counter, LowKick, HyperBeam, HyperBeam, None, None, None, None, None},
        {BodySlam, Submission, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Primeape),
        get_types(Species::Primeape)},
    RandomSetEntry{
        89,
        3,
        2,
        0,
        0,
        {Agility, BodySlam, FireBlast, None, None, None, None, None, None},
        {Flamethrower, Reflect, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Growlithe),
        get_types(Species::Growlithe)},
    RandomSetEntry{
        75,
        3,
        6,
        0,
        0,
        {BodySlam, FireBlast, HyperBeam, None, None, None, None, None, None},
        {Agility, Agility, Flamethrower, Flamethrower, Reflect, Rest, None,
         None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Arcanine),
        get_types(Species::Arcanine)},
    RandomSetEntry{
        86,
        4,
        0,
        0,
        0,
        {Amnesia, Blizzard, Hypnosis, Surf, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Poliwag),
        get_types(Species::Poliwag)},
    RandomSetEntry{
        79,
        4,
        0,
        0,
        0,
        {Amnesia, Blizzard, Hypnosis, Surf, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Poliwhirl),
        get_types(Species::Poliwhirl)},
    RandomSetEntry{74,
                   4,
                   0,
                   2,
                   4,
                   {BodySlam, Earthquake, Hypnosis, Submission, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {Blizzard, Surf, None},
                   {Amnesia, Blizzard, Hypnosis, Surf},
                   getImportantWeaknesses(Species::Poliwrath),
                   get_types(Species::Poliwrath)},
    RandomSetEntry{
        84,
        3,
        3,
        0,
        0,
        {Psychic, SeismicToss, ThunderWave, None, None, None, None, None, None},
        {Counter, Reflect, Substitute, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Abra),
        get_types(Species::Abra)},
    RandomSetEntry{
        74,
        3,
        5,
        0,
        0,
        {Psychic, Recover, ThunderWave, None, None, None, None, None, None},
        {Counter, Reflect, Reflect, SeismicToss, SeismicToss, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Kadabra),
        get_types(Species::Kadabra)},
    RandomSetEntry{
        68,
        3,
        5,
        0,
        0,
        {Psychic, Recover, ThunderWave, None, None, None, None, None, None},
        {Counter, Reflect, Reflect, SeismicToss, SeismicToss, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Alakazam),
        get_types(Species::Alakazam)},
    RandomSetEntry{
        89,
        3,
        3,
        0,
        0,
        {BodySlam, Earthquake, Submission, None, None, None, None, None, None},
        {Counter, RockSlide, RockSlide, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Machop),
        get_types(Species::Machop)},
    RandomSetEntry{
        81,
        3,
        3,
        0,
        0,
        {BodySlam, Earthquake, Submission, None, None, None, None, None, None},
        {Counter, RockSlide, RockSlide, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Machoke),
        get_types(Species::Machoke)},
    RandomSetEntry{
        76,
        3,
        5,
        0,
        0,
        {BodySlam, Earthquake, Submission, None, None, None, None, None, None},
        {Counter, HyperBeam, HyperBeam, RockSlide, RockSlide, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Machamp),
        get_types(Species::Machamp)},
    RandomSetEntry{
        88,
        3,
        3,
        0,
        0,
        {DoubleEdge, RazorLeaf, SleepPowder, None, None, None, None, None,
         None},
        {StunSpore, StunSpore, SwordsDance, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Bellsprout),
        get_types(Species::Bellsprout)},
    RandomSetEntry{
        80,
        3,
        3,
        0,
        0,
        {DoubleEdge, RazorLeaf, SleepPowder, None, None, None, None, None,
         None},
        {StunSpore, StunSpore, SwordsDance, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Weepinbell),
        get_types(Species::Weepinbell)},
    RandomSetEntry{
        74,
        3,
        6,
        0,
        0,
        {BodySlam, RazorLeaf, SleepPowder, None, None, None, None, None, None},
        {HyperBeam, StunSpore, StunSpore, StunSpore, SwordsDance, SwordsDance,
         None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Victreebel),
        get_types(Species::Victreebel)},
    RandomSetEntry{
        86,
        3,
        3,
        0,
        0,
        {Blizzard, MegaDrain, Surf, None, None, None, None, None, None},
        {HydroPump, HydroPump, Substitute, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Tentacool),
        get_types(Species::Tentacool)},
    RandomSetEntry{
        73,
        3,
        3,
        0,
        0,
        {Blizzard, HyperBeam, SwordsDance, None, None, None, None, None, None},
        {HydroPump, Surf, Surf, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Tentacruel),
        get_types(Species::Tentacruel)},
    RandomSetEntry{88,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, Earthquake, Explosion, RockSlide, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Geodude),
                   get_types(Species::Geodude)},
    RandomSetEntry{80,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, Earthquake, Explosion, RockSlide, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Graveler),
                   get_types(Species::Graveler)},
    RandomSetEntry{71,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, Earthquake, Explosion, RockSlide, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Golem),
                   get_types(Species::Golem)},
    RandomSetEntry{
        84,
        3,
        6,
        0,
        0,
        {Agility, BodySlam, FireBlast, None, None, None, None, None, None},
        {Reflect, Reflect, Reflect, Stomp, Substitute, Substitute, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Ponyta),
        get_types(Species::Ponyta)},
    RandomSetEntry{
        75,
        4,
        0,
        0,
        0,
        {Agility, BodySlam, FireBlast, HyperBeam, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Rapidash),
        get_types(Species::Rapidash)},
    RandomSetEntry{
        84,
        3,
        0,
        2,
        4,
        {Blizzard, Psychic, Surf, None, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {Amnesia, ThunderWave, None},
        {Amnesia, Rest, Surf, ThunderWave},
        getImportantWeaknesses(Species::Slowpoke),
        get_types(Species::Slowpoke)},
    RandomSetEntry{
        68,
        3,
        0,
        2,
        4,
        {Blizzard, Psychic, Surf, None, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {Amnesia, ThunderWave, None},
        {Amnesia, Rest, Surf, ThunderWave},
        getImportantWeaknesses(Species::Slowbro),
        get_types(Species::Slowbro)},
    RandomSetEntry{
        88,
        3,
        4,
        0,
        0,
        {Thunder, Thunderbolt, ThunderWave, None, None, None, None, None, None},
        {DoubleEdge, DoubleEdge, Mimic, Rest, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Magnemite),
        get_types(Species::Magnemite)},
    RandomSetEntry{
        76,
        3,
        5,
        0,
        0,
        {Thunder, Thunderbolt, ThunderWave, None, None, None, None, None, None},
        {DoubleEdge, HyperBeam, HyperBeam, Mimic, Rest, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Magneton),
        get_types(Species::Magneton)},
    RandomSetEntry{
        78,
        4,
        0,
        0,
        0,
        {Agility, BodySlam, Slash, SwordsDance, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Farfetchd),
        get_types(Species::Farfetchd)},
    RandomSetEntry{87,
                   4,
                   0,
                   0,
                   0,
                   {Agility, BodySlam, DoubleEdge, DrillPeck, None, None, None,
                    None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Doduo),
                   get_types(Species::Doduo)},
    RandomSetEntry{
        73,
        4,
        0,
        0,
        0,
        {Agility, BodySlam, DrillPeck, HyperBeam, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Dodrio),
        get_types(Species::Dodrio)},
    RandomSetEntry{
        88,
        4,
        0,
        0,
        0,
        {Blizzard, BodySlam, Rest, Surf, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Seel),
        get_types(Species::Seel)},
    RandomSetEntry{
        74,
        3,
        4,
        0,
        0,
        {Blizzard, BodySlam, Surf, None, None, None, None, None, None},
        {HyperBeam, Rest, Rest, Rest, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Dewgong),
        get_types(Species::Dewgong)},
    RandomSetEntry{90,
                   7,
                   0,
                   2,
                   0,
                   {FireBlast, FireBlast, MegaDrain, Sludge, Sludge, Sludge,
                    Thunderbolt, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {BodySlam, Explosion, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Grimer),
                   get_types(Species::Grimer)},
    RandomSetEntry{76,
                   9,
                   0,
                   2,
                   0,
                   {FireBlast, FireBlast, HyperBeam, MegaDrain, MegaDrain,
                    Sludge, Sludge, Sludge, Thunderbolt},
                   {None, None, None, None, None, None, None, None, None},
                   {BodySlam, Explosion, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Muk),
                   get_types(Species::Muk)},
    RandomSetEntry{
        90,
        4,
        0,
        0,
        0,
        {Blizzard, DoubleEdge, Explosion, Surf, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Shellder),
        get_types(Species::Shellder)},
    RandomSetEntry{
        70,
        3,
        3,
        0,
        0,
        {Blizzard, Explosion, Surf, None, None, None, None, None, None},
        {DoubleEdge, HyperBeam, HyperBeam, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Cloyster),
        get_types(Species::Cloyster)},
    RandomSetEntry{
        83,
        3,
        4,
        0,
        0,
        {Hypnosis, Psychic, Thunderbolt, None, None, None, None, None, None},
        {Explosion, Explosion, MegaDrain, NightShade, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Gastly),
        get_types(Species::Gastly)},
    RandomSetEntry{
        74,
        3,
        4,
        0,
        0,
        {Hypnosis, Psychic, Thunderbolt, None, None, None, None, None, None},
        {Explosion, Explosion, MegaDrain, NightShade, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Haunter),
        get_types(Species::Haunter)},
    RandomSetEntry{
        68,
        3,
        4,
        0,
        0,
        {Hypnosis, Psychic, Thunderbolt, None, None, None, None, None, None},
        {Explosion, Explosion, MegaDrain, NightShade, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Gengar),
        get_types(Species::Gengar)},
    RandomSetEntry{80,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, Earthquake, Explosion, RockSlide, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Onix),
                   get_types(Species::Onix)},
    RandomSetEntry{
        84,
        3,
        4,
        0,
        0,
        {Hypnosis, Psychic, ThunderWave, None, None, None, None, None, None},
        {Counter, Rest, SeismicToss, SeismicToss, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Drowzee),
        get_types(Species::Drowzee)},
    RandomSetEntry{
        72,
        3,
        5,
        0,
        0,
        {Hypnosis, Psychic, ThunderWave, None, None, None, None, None, None},
        {Counter, Rest, Rest, SeismicToss, SeismicToss, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Hypno),
        get_types(Species::Hypno)},
    RandomSetEntry{
        89,
        3,
        4,
        0,
        0,
        {BodySlam, Crabhammer, SwordsDance, None, None, None, None, None, None},
        {Blizzard, Blizzard, Blizzard, Stomp, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Krabby),
        get_types(Species::Krabby)},
    RandomSetEntry{76,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, Crabhammer, HyperBeam, SwordsDance, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Kingler),
                   get_types(Species::Kingler)},
    RandomSetEntry{
        88,
        3,
        2,
        0,
        0,
        {Explosion, Thunderbolt, ThunderWave, None, None, None, None, None,
         None},
        {TakeDown, Thunder, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Voltorb),
        get_types(Species::Voltorb)},
    RandomSetEntry{76,
                   3,
                   5,
                   0,
                   0,
                   {Explosion, Thunderbolt, ThunderWave, None, None, None, None,
                    None, None},
                   {HyperBeam, HyperBeam, TakeDown, Thunder, Thunder, None,
                    None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Electrode),
                   get_types(Species::Electrode)},
    RandomSetEntry{84,
                   4,
                   0,
                   0,
                   0,
                   {Explosion, Psychic, SleepPowder, StunSpore, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Exeggcute),
                   get_types(Species::Exeggcute)},
    RandomSetEntry{
        68,
        3,
        6,
        0,
        0,
        {Explosion, Psychic, SleepPowder, None, None, None, None, None, None},
        {DoubleEdge, HyperBeam, MegaDrain, StunSpore, StunSpore, StunSpore,
         None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Exeggutor),
        get_types(Species::Exeggutor)},
    RandomSetEntry{89,
                   4,
                   0,
                   0,
                   0,
                   {Blizzard, BodySlam, Earthquake, SeismicToss, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Cubone),
                   get_types(Species::Cubone)},
    RandomSetEntry{79,
                   4,
                   0,
                   0,
                   0,
                   {Blizzard, BodySlam, Earthquake, SeismicToss, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Marowak),
                   get_types(Species::Marowak)},
    RandomSetEntry{78,
                   3,
                   5,
                   0,
                   0,
                   {BodySlam, HighJumpKick, SeismicToss, None, None, None, None,
                    None, None},
                   {Counter, Counter, Meditate, MegaKick, RollingKick, None,
                    None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Hitmonlee),
                   get_types(Species::Hitmonlee)},
    RandomSetEntry{
        80,
        3,
        5,
        0,
        0,
        {BodySlam, SeismicToss, Submission, None, None, None, None, None, None},
        {Agility, Agility, Counter, Counter, MegaKick, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Hitmonchan),
        get_types(Species::Hitmonchan)},
    RandomSetEntry{
        78,
        3,
        4,
        0,
        0,
        {BodySlam, HyperBeam, SwordsDance, None, None, None, None, None, None},
        {Blizzard, Earthquake, Earthquake, Earthquake, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Lickitung),
        get_types(Species::Lickitung)},
    RandomSetEntry{90,
                   4,
                   0,
                   0,
                   0,
                   {Explosion, FireBlast, Sludge, Thunderbolt, None, None, None,
                    None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Koffing),
                   get_types(Species::Koffing)},
    RandomSetEntry{76,
                   4,
                   0,
                   0,
                   0,
                   {Explosion, FireBlast, Sludge, Thunderbolt, None, None, None,
                    None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Weezing),
                   get_types(Species::Weezing)},
    RandomSetEntry{84,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, Earthquake, RockSlide, Substitute, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Rhyhorn),
                   get_types(Species::Rhyhorn)},
    RandomSetEntry{68,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, Earthquake, RockSlide, Substitute, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Rhydon),
                   get_types(Species::Rhydon)},
    RandomSetEntry{
        68,
        3,
        7,
        0,
        0,
        {IceBeam, SoftBoiled, ThunderWave, None, None, None, None, None, None},
        {Counter, Reflect, SeismicToss, Sing, Thunderbolt, Thunderbolt,
         Thunderbolt, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Chansey),
        get_types(Species::Chansey)},
    RandomSetEntry{
        74,
        3,
        3,
        0,
        0,
        {BodySlam, MegaDrain, SleepPowder, None, None, None, None, None, None},
        {StunSpore, StunSpore, SwordsDance, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Tangela),
        get_types(Species::Tangela)},
    RandomSetEntry{
        73,
        3,
        4,
        0,
        0,
        {BodySlam, Earthquake, HyperBeam, None, None, None, None, None, None},
        {Counter, RockSlide, RockSlide, Surf, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Kangaskhan),
        get_types(Species::Kangaskhan)},
    RandomSetEntry{
        88,
        3,
        3,
        0,
        0,
        {Agility, Blizzard, Surf, None, None, None, None, None, None},
        {DoubleEdge, HydroPump, Smokescreen, None, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Horsea),
        get_types(Species::Horsea)},
    RandomSetEntry{
        77,
        3,
        5,
        0,
        0,
        {Agility, Blizzard, Surf, None, None, None, None, None, None},
        {DoubleEdge, HydroPump, HyperBeam, Rest, Smokescreen, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Seadra),
        get_types(Species::Seadra)},
    RandomSetEntry{
        88,
        4,
        0,
        0,
        0,
        {Agility, Blizzard, DoubleEdge, Surf, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Goldeen),
        get_types(Species::Goldeen)},
    RandomSetEntry{
        78,
        3,
        0,
        2,
        0,
        {Agility, DoubleEdge, HyperBeam, None, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {Blizzard, Surf, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Seaking),
        get_types(Species::Seaking)},
    RandomSetEntry{84,
                   3,
                   3,
                   1,
                   0,
                   {Blizzard, Thunderbolt, ThunderWave, None, None, None, None,
                    None, None},
                   {HydroPump, Surf, Surf, None, None, None, None, None, None},
                   {Recover, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Staryu),
                   get_types(Species::Staryu)},
    RandomSetEntry{
        68,
        3,
        4,
        2,
        0,
        {Blizzard, Psychic, Thunderbolt, None, None, None, None, None, None},
        {HydroPump, Psychic, Surf, Surf, None, None, None, None, None},
        {Recover, ThunderWave, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Starmie),
        get_types(Species::Starmie)},
    RandomSetEntry{75,
                   4,
                   0,
                   0,
                   0,
                   {Psychic, SeismicToss, Thunderbolt, ThunderWave, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::MrMime),
                   get_types(Species::MrMime)},
    RandomSetEntry{
        75,
        4,
        0,
        0,
        0,
        {Agility, HyperBeam, Slash, SwordsDance, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Scyther),
        get_types(Species::Scyther)},
    RandomSetEntry{
        68,
        3,
        5,
        0,
        0,
        {Blizzard, LovelyKiss, Psychic, None, None, None, None, None, None},
        {BodySlam, Counter, Counter, SeismicToss, Substitute, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Jynx),
        get_types(Species::Jynx)},
    RandomSetEntry{
        74,
        3,
        4,
        0,
        0,
        {Psychic, Thunderbolt, ThunderWave, None, None, None, None, None, None},
        {HyperBeam, SeismicToss, SeismicToss, SeismicToss, None, None, None,
         None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Electabuzz),
        get_types(Species::Electabuzz)},
    RandomSetEntry{
        76,
        3,
        3,
        0,
        0,
        {BodySlam, ConfuseRay, FireBlast, None, None, None, None, None, None},
        {HyperBeam, Psychic, SeismicToss, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Magmar),
        get_types(Species::Magmar)},
    RandomSetEntry{
        75,
        3,
        3,
        2,
        0,
        {BodySlam, BodySlam, Slash, None, None, None, None, None, None},
        {SeismicToss, Submission, Submission, None, None, None, None, None,
         None},
        {HyperBeam, SwordsDance, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Pinsir),
        get_types(Species::Pinsir)},
    RandomSetEntry{
        68,
        3,
        4,
        0,
        0,
        {BodySlam, Earthquake, HyperBeam, None, None, None, None, None, None},
        {Blizzard, Blizzard, Blizzard, Thunderbolt, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Tauros),
        get_types(Species::Tauros)},
    RandomSetEntry{},
    // magikarp  not found in data.json
    RandomSetEntry{74,
                   5,
                   3,
                   0,
                   0,
                   {Blizzard, BodySlam, BodySlam, HyperBeam, Thunderbolt, None,
                    None, None, None},
                   {HydroPump, Surf, Surf, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Gyarados),
                   get_types(Species::Gyarados)},
    RandomSetEntry{69,
                   4,
                   0,
                   2,
                   0,
                   {BodySlam, Rest, Sing, Surf, None, None, None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {Blizzard, Thunderbolt, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Lapras),
                   get_types(Species::Lapras)},
    RandomSetEntry{
        100,
        1,
        0,
        0,
        0,
        {Transform, None, None, None, None, None, None, None, None},
        {None, None, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Ditto),
        get_types(Species::Ditto)},
    RandomSetEntry{
        88,
        5,
        2,
        1,
        0,
        {DoubleEdge, DoubleEdge, QuickAttack, QuickAttack, Reflect, None, None,
         None, None},
        {SandAttack, TailWhip, None, None, None, None, None, None, None},
        {BodySlam, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Eevee),
        get_types(Species::Eevee)},
    RandomSetEntry{74,
                   3,
                   6,
                   0,
                   0,
                   {Blizzard, Rest, Surf, None, None, None, None, None, None},
                   {AcidArmor, BodySlam, BodySlam, BodySlam, HydroPump, Mimic,
                    None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Vaporeon),
                   get_types(Species::Vaporeon)},
    RandomSetEntry{69,
                   3,
                   5,
                   0,
                   0,
                   {BodySlam, Thunderbolt, ThunderWave, None, None, None, None,
                    None, None},
                   {Agility, Agility, DoubleKick, PinMissile, PinMissile, None,
                    None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Jolteon),
                   get_types(Species::Jolteon)},
    RandomSetEntry{76,
                   4,
                   0,
                   0,
                   0,
                   {BodySlam, FireBlast, HyperBeam, QuickAttack, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Flareon),
                   get_types(Species::Flareon)},
    RandomSetEntry{
        76,
        3,
        4,
        0,
        0,
        {Blizzard, Recover, ThunderWave, None, None, None, None, None, None},
        {DoubleEdge, Psychic, Thunderbolt, TriAttack, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Porygon),
        get_types(Species::Porygon)},
    RandomSetEntry{
        87,
        3,
        2,
        0,
        0,
        {Blizzard, BodySlam, Rest, None, None, None, None, None, None},
        {HydroPump, Surf, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Omanyte),
        get_types(Species::Omanyte)},
    RandomSetEntry{
        74,
        3,
        2,
        1,
        0,
        {BodySlam, Rest, SeismicToss, None, None, None, None, None, None},
        {HydroPump, Surf, None, None, None, None, None, None, None},
        {Blizzard, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Omastar),
        get_types(Species::Omastar)},
    RandomSetEntry{
        88,
        3,
        3,
        0,
        0,
        {Blizzard, BodySlam, Slash, None, None, None, None, None, None},
        {HydroPump, Surf, Surf, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Kabuto),
        get_types(Species::Kabuto)},
    RandomSetEntry{
        75,
        3,
        2,
        0,
        0,
        {HyperBeam, Surf, SwordsDance, None, None, None, None, None, None},
        {BodySlam, Slash, None, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Kabutops),
        get_types(Species::Kabutops)},
    RandomSetEntry{
        75,
        3,
        3,
        0,
        0,
        {DoubleEdge, FireBlast, HyperBeam, None, None, None, None, None, None},
        {Agility, SkyAttack, SkyAttack, None, None, None, None, None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Aerodactyl),
        get_types(Species::Aerodactyl)},
    RandomSetEntry{
        69,
        3,
        2,
        0,
        4,
        {Amnesia, Blizzard, BodySlam, None, None, None, None, None, None},
        {Rest, SelfDestruct, None, None, None, None, None, None, None},
        {None, None, None},
        {BodySlam, Earthquake, HyperBeam, SelfDestruct},
        getImportantWeaknesses(Species::Snorlax),
        get_types(Species::Snorlax)},
    RandomSetEntry{
        70,
        3,
        3,
        0,
        4,
        {Agility, Blizzard, HyperBeam, None, None, None, None, None, None},
        {IceBeam, Mimic, Reflect, None, None, None, None, None, None},
        {None, None, None},
        {Blizzard, IceBeam, Reflect, Rest},
        getImportantWeaknesses(Species::Articuno),
        get_types(Species::Articuno)},
    RandomSetEntry{68,
                   4,
                   0,
                   0,
                   0,
                   {Agility, DrillPeck, Thunderbolt, ThunderWave, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {None, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Zapdos),
                   get_types(Species::Zapdos)},
    RandomSetEntry{
        73,
        3,
        4,
        0,
        0,
        {Agility, FireBlast, HyperBeam, None, None, None, None, None, None},
        {DoubleEdge, DoubleEdge, DoubleEdge, Reflect, None, None, None, None,
         None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Moltres),
        get_types(Species::Moltres)},
    RandomSetEntry{89,
                   4,
                   0,
                   2,
                   0,
                   {BodySlam, HyperBeam, Thunderbolt, Thunderbolt, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {Blizzard, ThunderWave, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Dratini),
                   get_types(Species::Dratini)},
    RandomSetEntry{80,
                   4,
                   0,
                   2,
                   0,
                   {BodySlam, HyperBeam, Thunderbolt, Thunderbolt, None, None,
                    None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {Blizzard, ThunderWave, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Dragonair),
                   get_types(Species::Dragonair)},
    RandomSetEntry{74,
                   5,
                   0,
                   1,
                   0,
                   {BodySlam, HyperBeam, Thunderbolt, ThunderWave, ThunderWave,
                    None, None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {Blizzard, None, None},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Dragonite),
                   get_types(Species::Dragonite)},
    RandomSetEntry{
        60,
        3,
        4,
        0,
        0,
        {Amnesia, Psychic, Recover, None, None, None, None, None, None},
        {Blizzard, Thunderbolt, ThunderWave, ThunderWave, None, None, None,
         None, None},
        {None, None, None},
        {None, None, None, None},
        getImportantWeaknesses(Species::Mewtwo),
        get_types(Species::Mewtwo)},
    RandomSetEntry{64,
                   6,
                   0,
                   3,
                   0,
                   {Blizzard, Blizzard, Earthquake, Explosion, Explosion,
                    Thunderbolt, None, None, None},
                   {None, None, None, None, None, None, None, None, None},
                   {Psychic, SoftBoiled, ThunderWave},
                   {None, None, None, None},
                   getImportantWeaknesses(Species::Mew),
                   get_types(Species::Mew)},
}; // RANDOM_SET_DATA
}; // namespace RandomBattlesData
