#pragma once

#include <array>

#include <format/random-battles/data.h>

namespace RandomBattlesData {

using PKMN::Data::get_types;
using PKMN::Data::Move;
using PKMN::Data::Species;
using PKMN::Data::Type;

struct RandomSetEntry {
  static constexpr uint8_t max_moves{9};
  static constexpr uint8_t max_exclusive_moves{9};
  static constexpr uint8_t max_essential_moves{3};
  static constexpr uint8_t max_combo_moves{4};

  uint8_t level;
  uint8_t n_moves;
  uint8_t n_exclusive_moves;
  uint8_t n_essential_moves;
  uint8_t n_combo_moves;

  std::array<Move, max_moves> moves;
  std::array<Move, max_exclusive_moves> exclusive_moves;
  std::array<Move, max_essential_moves> essential_moves;
  std::array<Move, max_combo_moves> combo_moves;

  std::array<uint8_t, 6> weaknesses{};
  std::array<Type, 2> types{};
};

constexpr std::array<RandomSetEntry, 152> RANDOM_SET_DATA{

    RandomSetEntry{},
    // none  not found in data.json
    RandomSetEntry{89,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::RazorLeaf, Move::SleepPowder,
                    Move::SwordsDance, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Bulbasaur),
                   get_types(Species::Bulbasaur)},
    RandomSetEntry{80,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::RazorLeaf, Move::SleepPowder,
                    Move::SwordsDance, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Ivysaur),
                   get_types(Species::Ivysaur)},
    RandomSetEntry{
        74,
        3,
        3,
        0,
        0,
        {Move::BodySlam, Move::RazorLeaf, Move::SleepPowder, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::HyperBeam, Move::SwordsDance, Move::SwordsDance, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Venusaur),
        get_types(Species::Venusaur)},
    RandomSetEntry{
        90,
        5,
        0,
        2,
        4,
        {Move::Counter, Move::SeismicToss, Move::SeismicToss, Move::Slash,
         Move::Slash, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None, Move::None, Move::None,
         Move::None, Move::None, Move::None},
        {Move::BodySlam, Move::FireBlast, Move::None},
        {Move::BodySlam, Move::FireBlast, Move::Submission, Move::SwordsDance},
        getImportantWeaknesses(Species::Charmander),
        get_types(Species::Charmander)},
    RandomSetEntry{
        81,
        5,
        0,
        2,
        4,
        {Move::Counter, Move::SeismicToss, Move::SeismicToss, Move::Slash,
         Move::Slash, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None, Move::None, Move::None,
         Move::None, Move::None, Move::None},
        {Move::BodySlam, Move::FireBlast, Move::None},
        {Move::BodySlam, Move::FireBlast, Move::Submission, Move::SwordsDance},
        getImportantWeaknesses(Species::Charmeleon),
        get_types(Species::Charmeleon)},
    RandomSetEntry{
        74,
        4,
        0,
        0,
        4,
        {Move::BodySlam, Move::Earthquake, Move::FireBlast, Move::Slash,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None, Move::None, Move::None,
         Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::Earthquake, Move::FireBlast, Move::HyperBeam, Move::SwordsDance},
        getImportantWeaknesses(Species::Charizard),
        get_types(Species::Charizard)},
    RandomSetEntry{90,
                   2,
                   3,
                   2,
                   0,
                   {Move::BodySlam, Move::Counter, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::HydroPump, Move::Surf, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::Blizzard, Move::SeismicToss, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Squirtle),
                   get_types(Species::Squirtle)},
    RandomSetEntry{82,
                   3,
                   3,
                   2,
                   0,
                   {Move::Counter, Move::Rest, Move::SeismicToss, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::HydroPump, Move::Surf, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::Blizzard, Move::BodySlam, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Wartortle),
                   get_types(Species::Wartortle)},
    RandomSetEntry{75,
                   2,
                   3,
                   2,
                   0,
                   {Move::Earthquake, Move::Rest, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::HydroPump, Move::Surf, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::Blizzard, Move::BodySlam, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Blastoise),
                   get_types(Species::Blastoise)},
    RandomSetEntry{},
    // caterpie  not found in data.json
    RandomSetEntry{},
    // metapod  not found in data.json
    RandomSetEntry{
        77,
        3,
        4,
        0,
        0,
        {Move::Psychic, Move::SleepPowder, Move::StunSpore, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::DoubleEdge, Move::HyperBeam, Move::MegaDrain, Move::Substitute,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Butterfree),
        get_types(Species::Butterfree)},
    RandomSetEntry{},
    // weedle  not found in data.json
    RandomSetEntry{},
    // kakuna  not found in data.json
    RandomSetEntry{81,
                   3,
                   3,
                   0,
                   0,
                   {Move::HyperBeam, Move::SwordsDance, Move::Twineedle,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::Agility, Move::Agility, Move::MegaDrain, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Beedrill),
                   get_types(Species::Beedrill)},
    RandomSetEntry{
        93,
        5,
        3,
        1,
        4,
        {Move::Agility, Move::Agility, Move::QuickAttack, Move::QuickAttack,
         Move::SkyAttack, Move::None, Move::None, Move::None, Move::None},
        {Move::MirrorMove, Move::SandAttack, Move::Substitute, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::DoubleEdge, Move::None, Move::None},
        {Move::Agility, Move::DoubleEdge, Move::QuickAttack, Move::SkyAttack},
        getImportantWeaknesses(Species::Pidgey),
        get_types(Species::Pidgey)},
    RandomSetEntry{
        85,
        5,
        3,
        1,
        4,
        {Move::Agility, Move::Agility, Move::QuickAttack, Move::QuickAttack,
         Move::SkyAttack, Move::None, Move::None, Move::None, Move::None},
        {Move::MirrorMove, Move::SandAttack, Move::Substitute, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::DoubleEdge, Move::None, Move::None},
        {Move::Agility, Move::DoubleEdge, Move::QuickAttack, Move::SkyAttack},
        getImportantWeaknesses(Species::Pidgeotto),
        get_types(Species::Pidgeotto)},
    RandomSetEntry{76,
                   3,
                   9,
                   0,
                   0,
                   {Move::Agility, Move::DoubleEdge, Move::HyperBeam,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::MirrorMove, Move::Reflect, Move::SandAttack,
                    Move::SkyAttack, Move::SkyAttack, Move::Substitute,
                    Move::QuickAttack, Move::QuickAttack, Move::QuickAttack},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Pidgeot),
                   get_types(Species::Pidgeot)},
    RandomSetEntry{89,
                   3,
                   6,
                   0,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::SuperFang, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::DoubleEdge, Move::Thunderbolt, Move::Thunderbolt,
                    Move::Thunderbolt, Move::QuickAttack, Move::QuickAttack,
                    Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Rattata),
                   get_types(Species::Rattata)},
    RandomSetEntry{75,
                   4,
                   0,
                   0,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::HyperBeam,
                    Move::SuperFang, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Raticate),
                   get_types(Species::Raticate)},
    RandomSetEntry{89,
                   3,
                   4,
                   0,
                   0,
                   {Move::Agility, Move::DoubleEdge, Move::DrillPeck,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::Leer, Move::Mimic, Move::MirrorMove, Move::Substitute,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Spearow),
                   get_types(Species::Spearow)},
    RandomSetEntry{75,
                   4,
                   0,
                   0,
                   0,
                   {Move::Agility, Move::DoubleEdge, Move::DrillPeck,
                    Move::HyperBeam, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Fearow),
                   get_types(Species::Fearow)},
    RandomSetEntry{90,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::Earthquake, Move::Glare,
                    Move::RockSlide, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Ekans),
                   get_types(Species::Ekans)},
    RandomSetEntry{78,
                   3,
                   3,
                   0,
                   0,
                   {Move::Earthquake, Move::Glare, Move::HyperBeam, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::BodySlam, Move::RockSlide, Move::RockSlide,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Arbok),
                   get_types(Species::Arbok)},
    RandomSetEntry{
        87,
        3,
        4,
        0,
        0,
        {Move::Surf, Move::Thunderbolt, Move::ThunderWave, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Agility, Move::BodySlam, Move::SeismicToss, Move::SeismicToss,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Pikachu),
        get_types(Species::Pikachu)},
    RandomSetEntry{
        74,
        3,
        6,
        0,
        0,
        {Move::Surf, Move::Thunderbolt, Move::ThunderWave, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Agility, Move::BodySlam, Move::HyperBeam, Move::HyperBeam,
         Move::SeismicToss, Move::Thunder, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Raichu),
        get_types(Species::Raichu)},
    RandomSetEntry{88,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::Earthquake, Move::RockSlide,
                    Move::SwordsDance, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Sandshrew),
                   get_types(Species::Sandshrew)},
    RandomSetEntry{76,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::Earthquake, Move::RockSlide,
                    Move::SwordsDance, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Sandslash),
                   get_types(Species::Sandslash)},
    RandomSetEntry{90,
                   3,
                   2,
                   0,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::Thunderbolt,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::DoubleEdge, Move::DoubleKick, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::NidoranF),
                   get_types(Species::NidoranF)},
    RandomSetEntry{
        82,
        3,
        3,
        0,
        0,
        {Move::Blizzard, Move::BodySlam, Move::Thunderbolt, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::BubbleBeam, Move::DoubleEdge, Move::DoubleKick, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Nidorina),
        get_types(Species::Nidorina)},
    RandomSetEntry{
        74,
        3,
        3,
        0,
        0,
        {Move::Blizzard, Move::Earthquake, Move::Thunderbolt, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::BodySlam, Move::BodySlam, Move::Substitute, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Nidoqueen),
        get_types(Species::Nidoqueen)},
    RandomSetEntry{90,
                   3,
                   2,
                   0,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::Thunderbolt,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::DoubleEdge, Move::DoubleKick, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::NidoranM),
                   get_types(Species::NidoranM)},
    RandomSetEntry{
        82,
        3,
        3,
        0,
        0,
        {Move::Blizzard, Move::BodySlam, Move::Thunderbolt, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::BubbleBeam, Move::DoubleEdge, Move::DoubleKick, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Nidorino),
        get_types(Species::Nidorino)},
    RandomSetEntry{
        74,
        3,
        3,
        0,
        0,
        {Move::Blizzard, Move::Earthquake, Move::Thunderbolt, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::BodySlam, Move::RockSlide, Move::Substitute, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Nidoking),
        get_types(Species::Nidoking)},
    RandomSetEntry{
        88,
        4,
        6,
        2,
        0,
        {Move::BodySlam, Move::BodySlam, Move::SeismicToss, Move::Thunderbolt,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Blizzard, Move::Blizzard, Move::Counter, Move::Psychic,
         Move::Sing, Move::Sing, Move::None, Move::None, Move::None},
        {Move::Blizzard, Move::ThunderWave, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Clefairy),
        get_types(Species::Clefairy)},
    RandomSetEntry{
        74,
        5,
        7,
        1,
        0,
        {Move::BodySlam, Move::BodySlam, Move::Thunderbolt, Move::ThunderWave,
         Move::ThunderWave, Move::None, Move::None, Move::None, Move::None},
        {Move::Blizzard, Move::Counter, Move::HyperBeam, Move::HyperBeam,
         Move::Psychic, Move::Sing, Move::Sing, Move::None, Move::None},
        {Move::Blizzard, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Clefable),
        get_types(Species::Clefable)},
    RandomSetEntry{88,
                   3,
                   6,
                   0,
                   0,
                   {Move::BodySlam, Move::ConfuseRay, Move::FireBlast,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::Flamethrower, Move::Flamethrower, Move::QuickAttack,
                    Move::Reflect, Move::Substitute, Move::Substitute,
                    Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Vulpix),
                   get_types(Species::Vulpix)},
    RandomSetEntry{
        74,
        3,
        5,
        0,
        0,
        {Move::BodySlam, Move::ConfuseRay, Move::FireBlast, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Flamethrower, Move::HyperBeam, Move::Reflect, Move::Substitute,
         Move::Substitute, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Ninetales),
        get_types(Species::Ninetales)},
    RandomSetEntry{89,
                   2,
                   3,
                   2,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::Counter, Move::Sing, Move::ThunderWave, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::ThunderWave, Move::SeismicToss, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Jigglypuff),
                   get_types(Species::Jigglypuff)},
    RandomSetEntry{76,
                   3,
                   3,
                   0,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::ThunderWave,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::Counter, Move::HyperBeam, Move::Sing, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Wigglytuff),
                   get_types(Species::Wigglytuff)},
    RandomSetEntry{
        100,
        3,
        3,
        0,
        0,
        {Move::ConfuseRay, Move::DoubleEdge, Move::MegaDrain, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Substitute, Move::Substitute, Move::WingAttack, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Zubat),
        get_types(Species::Zubat)},
    RandomSetEntry{78,
                   4,
                   0,
                   0,
                   0,
                   {Move::ConfuseRay, Move::DoubleEdge, Move::HyperBeam,
                    Move::MegaDrain, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Golbat),
                   get_types(Species::Golbat)},
    RandomSetEntry{
        90,
        3,
        3,
        0,
        0,
        {Move::DoubleEdge, Move::MegaDrain, Move::SleepPowder, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::StunSpore, Move::StunSpore, Move::SwordsDance, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Oddish),
        get_types(Species::Oddish)},
    RandomSetEntry{
        82,
        3,
        3,
        0,
        0,
        {Move::DoubleEdge, Move::MegaDrain, Move::SleepPowder, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::StunSpore, Move::StunSpore, Move::SwordsDance, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Gloom),
        get_types(Species::Gloom)},
    RandomSetEntry{
        76,
        3,
        3,
        0,
        0,
        {Move::BodySlam, Move::MegaDrain, Move::SleepPowder, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::StunSpore, Move::StunSpore, Move::SwordsDance, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Vileplume),
        get_types(Species::Vileplume)},
    RandomSetEntry{90,
                   3,
                   3,
                   0,
                   0,
                   {Move::BodySlam, Move::MegaDrain, Move::Spore, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::StunSpore, Move::StunSpore, Move::SwordsDance,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Paras),
                   get_types(Species::Paras)},
    RandomSetEntry{77,
                   3,
                   7,
                   0,
                   0,
                   {Move::BodySlam, Move::MegaDrain, Move::Spore, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::HyperBeam, Move::Slash, Move::StunSpore,
                    Move::StunSpore, Move::StunSpore, Move::SwordsDance,
                    Move::SwordsDance, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Parasect),
                   get_types(Species::Parasect)},
    RandomSetEntry{88,
                   3,
                   2,
                   0,
                   0,
                   {Move::Psychic, Move::SleepPowder, Move::StunSpore,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::DoubleEdge, Move::MegaDrain, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Venonat),
                   get_types(Species::Venonat)},
    RandomSetEntry{74,
                   3,
                   2,
                   0,
                   0,
                   {Move::Psychic, Move::SleepPowder, Move::StunSpore,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::DoubleEdge, Move::MegaDrain, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Venomoth),
                   get_types(Species::Venomoth)},
    RandomSetEntry{86,
                   3,
                   2,
                   0,
                   0,
                   {Move::Earthquake, Move::RockSlide, Move::Slash, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::BodySlam, Move::Substitute, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Diglett),
                   get_types(Species::Diglett)},
    RandomSetEntry{73,
                   3,
                   2,
                   0,
                   0,
                   {Move::Earthquake, Move::RockSlide, Move::Slash, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::BodySlam, Move::Substitute, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Dugtrio),
                   get_types(Species::Dugtrio)},
    RandomSetEntry{85,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::BubbleBeam, Move::Slash,
                    Move::Thunderbolt, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Meowth),
                   get_types(Species::Meowth)},
    RandomSetEntry{73,
                   3,
                   2,
                   0,
                   0,
                   {Move::BodySlam, Move::BubbleBeam, Move::Slash, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::HyperBeam, Move::Thunderbolt, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Persian),
                   get_types(Species::Persian)},
    RandomSetEntry{89,
                   3,
                   5,
                   0,
                   0,
                   {Move::Amnesia, Move::Blizzard, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::BodySlam, Move::HydroPump, Move::Rest,
                    Move::SeismicToss, Move::SeismicToss, Move::None,
                    Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Psyduck),
                   get_types(Species::Psyduck)},
    RandomSetEntry{75,
                   3,
                   5,
                   0,
                   0,
                   {Move::Amnesia, Move::Blizzard, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::BodySlam, Move::HydroPump, Move::Rest, Move::Rest,
                    Move::SeismicToss, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Golduck),
                   get_types(Species::Golduck)},
    RandomSetEntry{89,
                   3,
                   3,
                   0,
                   0,
                   {Move::BodySlam, Move::RockSlide, Move::Submission,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::Counter, Move::LowKick, Move::MegaKick, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Mankey),
                   get_types(Species::Mankey)},
    RandomSetEntry{
        76,
        4,
        4,
        2,
        0,
        {Move::RockSlide, Move::RockSlide, Move::RockSlide, Move::Thunderbolt,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Counter, Move::LowKick, Move::HyperBeam, Move::HyperBeam,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::BodySlam, Move::Submission, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Primeape),
        get_types(Species::Primeape)},
    RandomSetEntry{89,
                   3,
                   2,
                   0,
                   0,
                   {Move::Agility, Move::BodySlam, Move::FireBlast, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::Flamethrower, Move::Reflect, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Growlithe),
                   get_types(Species::Growlithe)},
    RandomSetEntry{
        75,
        3,
        6,
        0,
        0,
        {Move::BodySlam, Move::FireBlast, Move::HyperBeam, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Agility, Move::Agility, Move::Flamethrower, Move::Flamethrower,
         Move::Reflect, Move::Rest, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Arcanine),
        get_types(Species::Arcanine)},
    RandomSetEntry{86,
                   4,
                   0,
                   0,
                   0,
                   {Move::Amnesia, Move::Blizzard, Move::Hypnosis, Move::Surf,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Poliwag),
                   get_types(Species::Poliwag)},
    RandomSetEntry{79,
                   4,
                   0,
                   0,
                   0,
                   {Move::Amnesia, Move::Blizzard, Move::Hypnosis, Move::Surf,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Poliwhirl),
                   get_types(Species::Poliwhirl)},
    RandomSetEntry{74,
                   4,
                   0,
                   2,
                   4,
                   {Move::BodySlam, Move::Earthquake, Move::Hypnosis,
                    Move::Submission, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::Blizzard, Move::Surf, Move::None},
                   {Move::Amnesia, Move::Blizzard, Move::Hypnosis, Move::Surf},
                   getImportantWeaknesses(Species::Poliwrath),
                   get_types(Species::Poliwrath)},
    RandomSetEntry{84,
                   3,
                   3,
                   0,
                   0,
                   {Move::Psychic, Move::SeismicToss, Move::ThunderWave,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::Counter, Move::Reflect, Move::Substitute, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Abra),
                   get_types(Species::Abra)},
    RandomSetEntry{74,
                   3,
                   5,
                   0,
                   0,
                   {Move::Psychic, Move::Recover, Move::ThunderWave, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::Counter, Move::Reflect, Move::Reflect,
                    Move::SeismicToss, Move::SeismicToss, Move::None,
                    Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Kadabra),
                   get_types(Species::Kadabra)},
    RandomSetEntry{68,
                   3,
                   5,
                   0,
                   0,
                   {Move::Psychic, Move::Recover, Move::ThunderWave, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::Counter, Move::Reflect, Move::Reflect,
                    Move::SeismicToss, Move::SeismicToss, Move::None,
                    Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Alakazam),
                   get_types(Species::Alakazam)},
    RandomSetEntry{89,
                   3,
                   3,
                   0,
                   0,
                   {Move::BodySlam, Move::Earthquake, Move::Submission,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::Counter, Move::RockSlide, Move::RockSlide, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Machop),
                   get_types(Species::Machop)},
    RandomSetEntry{81,
                   3,
                   3,
                   0,
                   0,
                   {Move::BodySlam, Move::Earthquake, Move::Submission,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::Counter, Move::RockSlide, Move::RockSlide, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Machoke),
                   get_types(Species::Machoke)},
    RandomSetEntry{
        76,
        3,
        5,
        0,
        0,
        {Move::BodySlam, Move::Earthquake, Move::Submission, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Counter, Move::HyperBeam, Move::HyperBeam, Move::RockSlide,
         Move::RockSlide, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Machamp),
        get_types(Species::Machamp)},
    RandomSetEntry{
        88,
        3,
        3,
        0,
        0,
        {Move::DoubleEdge, Move::RazorLeaf, Move::SleepPowder, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::StunSpore, Move::StunSpore, Move::SwordsDance, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Bellsprout),
        get_types(Species::Bellsprout)},
    RandomSetEntry{
        80,
        3,
        3,
        0,
        0,
        {Move::DoubleEdge, Move::RazorLeaf, Move::SleepPowder, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::StunSpore, Move::StunSpore, Move::SwordsDance, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Weepinbell),
        get_types(Species::Weepinbell)},
    RandomSetEntry{74,
                   3,
                   6,
                   0,
                   0,
                   {Move::BodySlam, Move::RazorLeaf, Move::SleepPowder,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::HyperBeam, Move::StunSpore, Move::StunSpore,
                    Move::StunSpore, Move::SwordsDance, Move::SwordsDance,
                    Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Victreebel),
                   get_types(Species::Victreebel)},
    RandomSetEntry{86,
                   3,
                   3,
                   0,
                   0,
                   {Move::Blizzard, Move::MegaDrain, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::HydroPump, Move::HydroPump, Move::Substitute,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Tentacool),
                   get_types(Species::Tentacool)},
    RandomSetEntry{73,
                   3,
                   3,
                   0,
                   0,
                   {Move::Blizzard, Move::HyperBeam, Move::SwordsDance,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::HydroPump, Move::Surf, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Tentacruel),
                   get_types(Species::Tentacruel)},
    RandomSetEntry{88,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::Earthquake, Move::Explosion,
                    Move::RockSlide, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Geodude),
                   get_types(Species::Geodude)},
    RandomSetEntry{80,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::Earthquake, Move::Explosion,
                    Move::RockSlide, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Graveler),
                   get_types(Species::Graveler)},
    RandomSetEntry{71,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::Earthquake, Move::Explosion,
                    Move::RockSlide, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Golem),
                   get_types(Species::Golem)},
    RandomSetEntry{84,
                   3,
                   6,
                   0,
                   0,
                   {Move::Agility, Move::BodySlam, Move::FireBlast, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::Reflect, Move::Reflect, Move::Reflect, Move::Stomp,
                    Move::Substitute, Move::Substitute, Move::None, Move::None,
                    Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Ponyta),
                   get_types(Species::Ponyta)},
    RandomSetEntry{75,
                   4,
                   0,
                   0,
                   0,
                   {Move::Agility, Move::BodySlam, Move::FireBlast,
                    Move::HyperBeam, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Rapidash),
                   get_types(Species::Rapidash)},
    RandomSetEntry{84,
                   3,
                   0,
                   2,
                   4,
                   {Move::Blizzard, Move::Psychic, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::Amnesia, Move::ThunderWave, Move::None},
                   {Move::Amnesia, Move::Rest, Move::Surf, Move::ThunderWave},
                   getImportantWeaknesses(Species::Slowpoke),
                   get_types(Species::Slowpoke)},
    RandomSetEntry{68,
                   3,
                   0,
                   2,
                   4,
                   {Move::Blizzard, Move::Psychic, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::Amnesia, Move::ThunderWave, Move::None},
                   {Move::Amnesia, Move::Rest, Move::Surf, Move::ThunderWave},
                   getImportantWeaknesses(Species::Slowbro),
                   get_types(Species::Slowbro)},
    RandomSetEntry{88,
                   3,
                   4,
                   0,
                   0,
                   {Move::Thunder, Move::Thunderbolt, Move::ThunderWave,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::DoubleEdge, Move::DoubleEdge, Move::Mimic, Move::Rest,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Magnemite),
                   get_types(Species::Magnemite)},
    RandomSetEntry{
        76,
        3,
        5,
        0,
        0,
        {Move::Thunder, Move::Thunderbolt, Move::ThunderWave, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::DoubleEdge, Move::HyperBeam, Move::HyperBeam, Move::Mimic,
         Move::Rest, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Magneton),
        get_types(Species::Magneton)},
    RandomSetEntry{78,
                   4,
                   0,
                   0,
                   0,
                   {Move::Agility, Move::BodySlam, Move::Slash,
                    Move::SwordsDance, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Farfetchd),
                   get_types(Species::Farfetchd)},
    RandomSetEntry{87,
                   4,
                   0,
                   0,
                   0,
                   {Move::Agility, Move::BodySlam, Move::DoubleEdge,
                    Move::DrillPeck, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Doduo),
                   get_types(Species::Doduo)},
    RandomSetEntry{73,
                   4,
                   0,
                   0,
                   0,
                   {Move::Agility, Move::BodySlam, Move::DrillPeck,
                    Move::HyperBeam, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Dodrio),
                   get_types(Species::Dodrio)},
    RandomSetEntry{88,
                   4,
                   0,
                   0,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::Rest, Move::Surf,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Seel),
                   get_types(Species::Seel)},
    RandomSetEntry{74,
                   3,
                   4,
                   0,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::HyperBeam, Move::Rest, Move::Rest, Move::Rest,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Dewgong),
                   get_types(Species::Dewgong)},
    RandomSetEntry{90,
                   7,
                   0,
                   2,
                   0,
                   {Move::FireBlast, Move::FireBlast, Move::MegaDrain,
                    Move::Sludge, Move::Sludge, Move::Sludge, Move::Thunderbolt,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::BodySlam, Move::Explosion, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Grimer),
                   get_types(Species::Grimer)},
    RandomSetEntry{76,
                   9,
                   0,
                   2,
                   0,
                   {Move::FireBlast, Move::FireBlast, Move::HyperBeam,
                    Move::MegaDrain, Move::MegaDrain, Move::Sludge,
                    Move::Sludge, Move::Sludge, Move::Thunderbolt},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::BodySlam, Move::Explosion, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Muk),
                   get_types(Species::Muk)},
    RandomSetEntry{90,
                   4,
                   0,
                   0,
                   0,
                   {Move::Blizzard, Move::DoubleEdge, Move::Explosion,
                    Move::Surf, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Shellder),
                   get_types(Species::Shellder)},
    RandomSetEntry{70,
                   3,
                   3,
                   0,
                   0,
                   {Move::Blizzard, Move::Explosion, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::DoubleEdge, Move::HyperBeam, Move::HyperBeam,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Cloyster),
                   get_types(Species::Cloyster)},
    RandomSetEntry{
        83,
        3,
        4,
        0,
        0,
        {Move::Hypnosis, Move::Psychic, Move::Thunderbolt, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Explosion, Move::Explosion, Move::MegaDrain, Move::NightShade,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Gastly),
        get_types(Species::Gastly)},
    RandomSetEntry{
        74,
        3,
        4,
        0,
        0,
        {Move::Hypnosis, Move::Psychic, Move::Thunderbolt, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Explosion, Move::Explosion, Move::MegaDrain, Move::NightShade,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Haunter),
        get_types(Species::Haunter)},
    RandomSetEntry{
        68,
        3,
        4,
        0,
        0,
        {Move::Hypnosis, Move::Psychic, Move::Thunderbolt, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Explosion, Move::Explosion, Move::MegaDrain, Move::NightShade,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Gengar),
        get_types(Species::Gengar)},
    RandomSetEntry{80,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::Earthquake, Move::Explosion,
                    Move::RockSlide, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Onix),
                   get_types(Species::Onix)},
    RandomSetEntry{
        84,
        3,
        4,
        0,
        0,
        {Move::Hypnosis, Move::Psychic, Move::ThunderWave, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Counter, Move::Rest, Move::SeismicToss, Move::SeismicToss,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Drowzee),
        get_types(Species::Drowzee)},
    RandomSetEntry{
        72,
        3,
        5,
        0,
        0,
        {Move::Hypnosis, Move::Psychic, Move::ThunderWave, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Counter, Move::Rest, Move::Rest, Move::SeismicToss,
         Move::SeismicToss, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Hypno),
        get_types(Species::Hypno)},
    RandomSetEntry{89,
                   3,
                   4,
                   0,
                   0,
                   {Move::BodySlam, Move::Crabhammer, Move::SwordsDance,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::Blizzard, Move::Blizzard, Move::Blizzard, Move::Stomp,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Krabby),
                   get_types(Species::Krabby)},
    RandomSetEntry{76,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::Crabhammer, Move::HyperBeam,
                    Move::SwordsDance, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Kingler),
                   get_types(Species::Kingler)},
    RandomSetEntry{88,
                   3,
                   2,
                   0,
                   0,
                   {Move::Explosion, Move::Thunderbolt, Move::ThunderWave,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::TakeDown, Move::Thunder, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Voltorb),
                   get_types(Species::Voltorb)},
    RandomSetEntry{
        76,
        3,
        5,
        0,
        0,
        {Move::Explosion, Move::Thunderbolt, Move::ThunderWave, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::HyperBeam, Move::HyperBeam, Move::TakeDown, Move::Thunder,
         Move::Thunder, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Electrode),
        get_types(Species::Electrode)},
    RandomSetEntry{84,
                   4,
                   0,
                   0,
                   0,
                   {Move::Explosion, Move::Psychic, Move::SleepPowder,
                    Move::StunSpore, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Exeggcute),
                   get_types(Species::Exeggcute)},
    RandomSetEntry{
        68,
        3,
        6,
        0,
        0,
        {Move::Explosion, Move::Psychic, Move::SleepPowder, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::DoubleEdge, Move::HyperBeam, Move::MegaDrain, Move::StunSpore,
         Move::StunSpore, Move::StunSpore, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Exeggutor),
        get_types(Species::Exeggutor)},
    RandomSetEntry{89,
                   4,
                   0,
                   0,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::Earthquake,
                    Move::SeismicToss, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Cubone),
                   get_types(Species::Cubone)},
    RandomSetEntry{79,
                   4,
                   0,
                   0,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::Earthquake,
                    Move::SeismicToss, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Marowak),
                   get_types(Species::Marowak)},
    RandomSetEntry{
        78,
        3,
        5,
        0,
        0,
        {Move::BodySlam, Move::HighJumpKick, Move::SeismicToss, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Counter, Move::Counter, Move::Meditate, Move::MegaKick,
         Move::RollingKick, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Hitmonlee),
        get_types(Species::Hitmonlee)},
    RandomSetEntry{
        80,
        3,
        5,
        0,
        0,
        {Move::BodySlam, Move::SeismicToss, Move::Submission, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Agility, Move::Agility, Move::Counter, Move::Counter,
         Move::MegaKick, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Hitmonchan),
        get_types(Species::Hitmonchan)},
    RandomSetEntry{
        78,
        3,
        4,
        0,
        0,
        {Move::BodySlam, Move::HyperBeam, Move::SwordsDance, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Blizzard, Move::Earthquake, Move::Earthquake, Move::Earthquake,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Lickitung),
        get_types(Species::Lickitung)},
    RandomSetEntry{90,
                   4,
                   0,
                   0,
                   0,
                   {Move::Explosion, Move::FireBlast, Move::Sludge,
                    Move::Thunderbolt, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Koffing),
                   get_types(Species::Koffing)},
    RandomSetEntry{76,
                   4,
                   0,
                   0,
                   0,
                   {Move::Explosion, Move::FireBlast, Move::Sludge,
                    Move::Thunderbolt, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Weezing),
                   get_types(Species::Weezing)},
    RandomSetEntry{84,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::Earthquake, Move::RockSlide,
                    Move::Substitute, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Rhyhorn),
                   get_types(Species::Rhyhorn)},
    RandomSetEntry{68,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::Earthquake, Move::RockSlide,
                    Move::Substitute, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Rhydon),
                   get_types(Species::Rhydon)},
    RandomSetEntry{68,
                   3,
                   7,
                   0,
                   0,
                   {Move::IceBeam, Move::SoftBoiled, Move::ThunderWave,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::Counter, Move::Reflect, Move::SeismicToss, Move::Sing,
                    Move::Thunderbolt, Move::Thunderbolt, Move::Thunderbolt,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Chansey),
                   get_types(Species::Chansey)},
    RandomSetEntry{
        74,
        3,
        3,
        0,
        0,
        {Move::BodySlam, Move::MegaDrain, Move::SleepPowder, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::StunSpore, Move::StunSpore, Move::SwordsDance, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Tangela),
        get_types(Species::Tangela)},
    RandomSetEntry{73,
                   3,
                   4,
                   0,
                   0,
                   {Move::BodySlam, Move::Earthquake, Move::HyperBeam,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::Counter, Move::RockSlide, Move::RockSlide, Move::Surf,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Kangaskhan),
                   get_types(Species::Kangaskhan)},
    RandomSetEntry{88,
                   3,
                   3,
                   0,
                   0,
                   {Move::Agility, Move::Blizzard, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::DoubleEdge, Move::HydroPump, Move::Smokescreen,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Horsea),
                   get_types(Species::Horsea)},
    RandomSetEntry{77,
                   3,
                   5,
                   0,
                   0,
                   {Move::Agility, Move::Blizzard, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::DoubleEdge, Move::HydroPump, Move::HyperBeam,
                    Move::Rest, Move::Smokescreen, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Seadra),
                   get_types(Species::Seadra)},
    RandomSetEntry{88,
                   4,
                   0,
                   0,
                   0,
                   {Move::Agility, Move::Blizzard, Move::DoubleEdge, Move::Surf,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Goldeen),
                   get_types(Species::Goldeen)},
    RandomSetEntry{78,
                   3,
                   0,
                   2,
                   0,
                   {Move::Agility, Move::DoubleEdge, Move::HyperBeam,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::Blizzard, Move::Surf, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Seaking),
                   get_types(Species::Seaking)},
    RandomSetEntry{84,
                   3,
                   3,
                   1,
                   0,
                   {Move::Blizzard, Move::Thunderbolt, Move::ThunderWave,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::HydroPump, Move::Surf, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::Recover, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Staryu),
                   get_types(Species::Staryu)},
    RandomSetEntry{68,
                   3,
                   4,
                   2,
                   0,
                   {Move::Blizzard, Move::Psychic, Move::Thunderbolt,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::HydroPump, Move::Psychic, Move::Surf, Move::Surf,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::Recover, Move::ThunderWave, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Starmie),
                   get_types(Species::Starmie)},
    RandomSetEntry{75,
                   4,
                   0,
                   0,
                   0,
                   {Move::Psychic, Move::SeismicToss, Move::Thunderbolt,
                    Move::ThunderWave, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::MrMime),
                   get_types(Species::MrMime)},
    RandomSetEntry{75,
                   4,
                   0,
                   0,
                   0,
                   {Move::Agility, Move::HyperBeam, Move::Slash,
                    Move::SwordsDance, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Scyther),
                   get_types(Species::Scyther)},
    RandomSetEntry{68,
                   3,
                   5,
                   0,
                   0,
                   {Move::Blizzard, Move::LovelyKiss, Move::Psychic, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::BodySlam, Move::Counter, Move::Counter,
                    Move::SeismicToss, Move::Substitute, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Jynx),
                   get_types(Species::Jynx)},
    RandomSetEntry{74,
                   3,
                   4,
                   0,
                   0,
                   {Move::Psychic, Move::Thunderbolt, Move::ThunderWave,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::HyperBeam, Move::SeismicToss, Move::SeismicToss,
                    Move::SeismicToss, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Electabuzz),
                   get_types(Species::Electabuzz)},
    RandomSetEntry{
        76,
        3,
        3,
        0,
        0,
        {Move::BodySlam, Move::ConfuseRay, Move::FireBlast, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::HyperBeam, Move::Psychic, Move::SeismicToss, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Magmar),
        get_types(Species::Magmar)},
    RandomSetEntry{75,
                   3,
                   3,
                   2,
                   0,
                   {Move::BodySlam, Move::BodySlam, Move::Slash, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::SeismicToss, Move::Submission, Move::Submission,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::HyperBeam, Move::SwordsDance, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Pinsir),
                   get_types(Species::Pinsir)},
    RandomSetEntry{
        68,
        3,
        4,
        0,
        0,
        {Move::BodySlam, Move::Earthquake, Move::HyperBeam, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Blizzard, Move::Blizzard, Move::Blizzard, Move::Thunderbolt,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Tauros),
        get_types(Species::Tauros)},
    RandomSetEntry{},
    // magikarp  not found in data.json
    RandomSetEntry{74,
                   5,
                   3,
                   0,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::BodySlam,
                    Move::HyperBeam, Move::Thunderbolt, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::HydroPump, Move::Surf, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Gyarados),
                   get_types(Species::Gyarados)},
    RandomSetEntry{69,
                   4,
                   0,
                   2,
                   0,
                   {Move::BodySlam, Move::Rest, Move::Sing, Move::Surf,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::Blizzard, Move::Thunderbolt, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Lapras),
                   get_types(Species::Lapras)},
    RandomSetEntry{
        100,
        1,
        0,
        0,
        0,
        {Move::Transform, Move::None, Move::None, Move::None, Move::None,
         Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None, Move::None, Move::None,
         Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Ditto),
        get_types(Species::Ditto)},
    RandomSetEntry{88,
                   5,
                   2,
                   1,
                   0,
                   {Move::DoubleEdge, Move::DoubleEdge, Move::QuickAttack,
                    Move::QuickAttack, Move::Reflect, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::SandAttack, Move::TailWhip, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::BodySlam, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Eevee),
                   get_types(Species::Eevee)},
    RandomSetEntry{74,
                   3,
                   6,
                   0,
                   0,
                   {Move::Blizzard, Move::Rest, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::AcidArmor, Move::BodySlam, Move::BodySlam,
                    Move::BodySlam, Move::HydroPump, Move::Mimic, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Vaporeon),
                   get_types(Species::Vaporeon)},
    RandomSetEntry{
        69,
        3,
        5,
        0,
        0,
        {Move::BodySlam, Move::Thunderbolt, Move::ThunderWave, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::Agility, Move::Agility, Move::DoubleKick, Move::PinMissile,
         Move::PinMissile, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Jolteon),
        get_types(Species::Jolteon)},
    RandomSetEntry{76,
                   4,
                   0,
                   0,
                   0,
                   {Move::BodySlam, Move::FireBlast, Move::HyperBeam,
                    Move::QuickAttack, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Flareon),
                   get_types(Species::Flareon)},
    RandomSetEntry{
        76,
        3,
        4,
        0,
        0,
        {Move::Blizzard, Move::Recover, Move::ThunderWave, Move::None,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::DoubleEdge, Move::Psychic, Move::Thunderbolt, Move::TriAttack,
         Move::None, Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None, Move::None},
        getImportantWeaknesses(Species::Porygon),
        get_types(Species::Porygon)},
    RandomSetEntry{87,
                   3,
                   2,
                   0,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::Rest, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::HydroPump, Move::Surf, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Omanyte),
                   get_types(Species::Omanyte)},
    RandomSetEntry{74,
                   3,
                   2,
                   1,
                   0,
                   {Move::BodySlam, Move::Rest, Move::SeismicToss, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::HydroPump, Move::Surf, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::Blizzard, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Omastar),
                   get_types(Species::Omastar)},
    RandomSetEntry{88,
                   3,
                   3,
                   0,
                   0,
                   {Move::Blizzard, Move::BodySlam, Move::Slash, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::HydroPump, Move::Surf, Move::Surf, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Kabuto),
                   get_types(Species::Kabuto)},
    RandomSetEntry{75,
                   3,
                   2,
                   0,
                   0,
                   {Move::HyperBeam, Move::Surf, Move::SwordsDance, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::BodySlam, Move::Slash, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Kabutops),
                   get_types(Species::Kabutops)},
    RandomSetEntry{75,
                   3,
                   3,
                   0,
                   0,
                   {Move::DoubleEdge, Move::FireBlast, Move::HyperBeam,
                    Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None},
                   {Move::Agility, Move::SkyAttack, Move::SkyAttack, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Aerodactyl),
                   get_types(Species::Aerodactyl)},
    RandomSetEntry{
        69,
        3,
        2,
        0,
        4,
        {Move::Amnesia, Move::Blizzard, Move::BodySlam, Move::None, Move::None,
         Move::None, Move::None, Move::None, Move::None},
        {Move::Rest, Move::SelfDestruct, Move::None, Move::None, Move::None,
         Move::None, Move::None, Move::None, Move::None},
        {Move::None, Move::None, Move::None},
        {Move::BodySlam, Move::Earthquake, Move::HyperBeam, Move::SelfDestruct},
        getImportantWeaknesses(Species::Snorlax),
        get_types(Species::Snorlax)},
    RandomSetEntry{70,
                   3,
                   3,
                   0,
                   4,
                   {Move::Agility, Move::Blizzard, Move::HyperBeam, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::IceBeam, Move::Mimic, Move::Reflect, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::Blizzard, Move::IceBeam, Move::Reflect, Move::Rest},
                   getImportantWeaknesses(Species::Articuno),
                   get_types(Species::Articuno)},
    RandomSetEntry{68,
                   4,
                   0,
                   0,
                   0,
                   {Move::Agility, Move::DrillPeck, Move::Thunderbolt,
                    Move::ThunderWave, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Zapdos),
                   get_types(Species::Zapdos)},
    RandomSetEntry{73,
                   3,
                   4,
                   0,
                   0,
                   {Move::Agility, Move::FireBlast, Move::HyperBeam, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::DoubleEdge, Move::DoubleEdge, Move::DoubleEdge,
                    Move::Reflect, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Moltres),
                   get_types(Species::Moltres)},
    RandomSetEntry{89,
                   4,
                   0,
                   2,
                   0,
                   {Move::BodySlam, Move::HyperBeam, Move::Thunderbolt,
                    Move::Thunderbolt, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::Blizzard, Move::ThunderWave, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Dratini),
                   get_types(Species::Dratini)},
    RandomSetEntry{80,
                   4,
                   0,
                   2,
                   0,
                   {Move::BodySlam, Move::HyperBeam, Move::Thunderbolt,
                    Move::Thunderbolt, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::Blizzard, Move::ThunderWave, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Dragonair),
                   get_types(Species::Dragonair)},
    RandomSetEntry{74,
                   5,
                   0,
                   1,
                   0,
                   {Move::BodySlam, Move::HyperBeam, Move::Thunderbolt,
                    Move::ThunderWave, Move::ThunderWave, Move::None,
                    Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::Blizzard, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Dragonite),
                   get_types(Species::Dragonite)},
    RandomSetEntry{60,
                   3,
                   4,
                   0,
                   0,
                   {Move::Amnesia, Move::Psychic, Move::Recover, Move::None,
                    Move::None, Move::None, Move::None, Move::None, Move::None},
                   {Move::Blizzard, Move::Thunderbolt, Move::ThunderWave,
                    Move::ThunderWave, Move::None, Move::None, Move::None,
                    Move::None, Move::None},
                   {Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Mewtwo),
                   get_types(Species::Mewtwo)},
    RandomSetEntry{64,
                   6,
                   0,
                   3,
                   0,
                   {Move::Blizzard, Move::Blizzard, Move::Earthquake,
                    Move::Explosion, Move::Explosion, Move::Thunderbolt,
                    Move::None, Move::None, Move::None},
                   {Move::None, Move::None, Move::None, Move::None, Move::None,
                    Move::None, Move::None, Move::None, Move::None},
                   {Move::Psychic, Move::SoftBoiled, Move::ThunderWave},
                   {Move::None, Move::None, Move::None, Move::None},
                   getImportantWeaknesses(Species::Mew),
                   get_types(Species::Mew)},
}; // RANDOM_SET_DATA
}; // namespace RandomBattlesData
